/*
 * Copyright (c) 2021-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file hks_error_code.h
 *
 * @brief Declares huks error code.
 *
 * @since 8
 */

#ifndef HKS_ERROR_CODE_H
#define HKS_ERROR_CODE_H

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief hks error code
 */
enum HksErrorCode {
    HKS_SUCCESS = 0,
    HKS_FAILURE = -1,
    HKS_ERROR_BAD_STATE = -2,
    HKS_ERROR_INVALID_ARGUMENT = -3,
    HKS_ERROR_NOT_SUPPORTED = -4,
    HKS_ERROR_NO_PERMISSION = -5,
    HKS_ERROR_INSUFFICIENT_DATA = -6,
    HKS_ERROR_BUFFER_TOO_SMALL = -7,
    HKS_ERROR_INSUFFICIENT_MEMORY = -8,
    HKS_ERROR_COMMUNICATION_FAILURE = -9,
    HKS_ERROR_STORAGE_FAILURE = -10,
    HKS_ERROR_HARDWARE_FAILURE = -11,
    HKS_ERROR_ALREADY_EXISTS = -12,
    HKS_ERROR_NOT_EXIST = -13,
    HKS_ERROR_NULL_POINTER = -14,
    HKS_ERROR_FILE_SIZE_FAIL = -15,
    HKS_ERROR_READ_FILE_FAIL = -16,
    HKS_ERROR_INVALID_PUBLIC_KEY = -17,
    HKS_ERROR_INVALID_PRIVATE_KEY = -18,
    HKS_ERROR_INVALID_KEY_INFO = -19,
    HKS_ERROR_HASH_NOT_EQUAL = -20,
    HKS_ERROR_MALLOC_FAIL = -21,
    HKS_ERROR_WRITE_FILE_FAIL = -22,
    HKS_ERROR_REMOVE_FILE_FAIL = -23,
    HKS_ERROR_OPEN_FILE_FAIL = -24,
    HKS_ERROR_CLOSE_FILE_FAIL = -25,
    HKS_ERROR_MAKE_DIR_FAIL = -26,
    HKS_ERROR_INVALID_KEY_FILE = -27,
    HKS_ERROR_IPC_MSG_FAIL = -28,
    HKS_ERROR_REQUEST_OVERFLOWS = -29,
    HKS_ERROR_PARAM_NOT_EXIST = -30,
    HKS_ERROR_CRYPTO_ENGINE_ERROR = -31,
    HKS_ERROR_COMMUNICATION_TIMEOUT = -32,
    HKS_ERROR_IPC_INIT_FAIL = -33,
    HKS_ERROR_IPC_DLOPEN_FAIL = -34,
    HKS_ERROR_EFUSE_READ_FAIL = -35,
    HKS_ERROR_NEW_ROOT_KEY_MATERIAL_EXIST = -36,
    HKS_ERROR_UPDATE_ROOT_KEY_MATERIAL_FAIL = -37,
    HKS_ERROR_VERIFICATION_FAILED = -38,
    HKS_ERROR_SESSION_REACHED_LIMIT = -39,

    HKS_ERROR_GET_USERIAM_SECINFO_FAILED = -40,
    HKS_ERROR_GET_USERIAM_AUTHINFO_FAILED = -41,
    HKS_ERROR_USER_AUTH_TYPE_NOT_SUPPORT = -42,
    HKS_ERROR_KEY_AUTH_FAILED = -43,
    HKS_ERROR_DEVICE_NO_CREDENTIAL = -44,
    HKS_ERROR_API_NOT_SUPPORTED = -45,
    HKS_ERROR_KEY_AUTH_PERMANENTLY_INVALIDATED = -46,
    HKS_ERROR_KEY_AUTH_VERIFY_FAILED = -47,
    HKS_ERROR_KEY_AUTH_TIME_OUT = -48,

    HKS_ERROR_CREDENTIAL_NOT_EXIST = -49,

    HKS_ERROR_CHECK_GET_ALG_FAIL = -100,
    HKS_ERROR_CHECK_GET_KEY_SIZE_FAIL = -101,
    HKS_ERROR_CHECK_GET_PADDING_FAIL = -102,
    HKS_ERROR_CHECK_GET_PURPOSE_FAIL = -103,
    HKS_ERROR_CHECK_GET_DIGEST_FAIL = -104,
    HKS_ERROR_CHECK_GET_MODE_FAIL = -105,
    HKS_ERROR_CHECK_GET_NONCE_FAIL = -106,
    HKS_ERROR_CHECK_GET_AAD_FAIL = -107,
    HKS_ERROR_CHECK_GET_IV_FAIL = -108,
    HKS_ERROR_CHECK_GET_AE_TAG_FAIL = -109,
    HKS_ERROR_CHECK_GET_SALT_FAIL = -110,
    HKS_ERROR_CHECK_GET_ITERATION_FAIL = -111,
    HKS_ERROR_INVALID_ALGORITHM = -112,
    HKS_ERROR_INVALID_KEY_SIZE = -113,
    HKS_ERROR_INVALID_PADDING = -114,
    HKS_ERROR_INVALID_PURPOSE = -115,
    HKS_ERROR_INVALID_MODE = -116,
    HKS_ERROR_INVALID_DIGEST =  -117,
    HKS_ERROR_INVALID_SIGNATURE_SIZE = -118,
    HKS_ERROR_INVALID_IV = -119,
    HKS_ERROR_INVALID_AAD = -120,
    HKS_ERROR_INVALID_NONCE = -121,
    HKS_ERROR_INVALID_AE_TAG = -122,
    HKS_ERROR_INVALID_SALT = -123,
    HKS_ERROR_INVALID_ITERATION = -124,
    HKS_ERROR_INVALID_OPERATION = -125,
    HKS_ERROR_INVALID_WRAPPED_FORMAT = -126,
    HKS_ERROR_INVALID_USAGE_OF_KEY = -127,
    HKS_ERROR_CHECK_GET_AUTH_TYP_FAILED = -128,
    HKS_ERROR_CHECK_GET_CHALLENGE_TYPE_FAILED = -129,
    HKS_ERROR_CHECK_GET_ACCESS_TYPE_FAILED = -130,
    HKS_ERROR_CHECK_GET_AUTH_TOKEN_FAILED = -131,
    HKS_ERROR_INVALID_TIME_OUT = -132,
    HKS_ERROR_INVALID_AUTH_TYPE = -133,
    HKS_ERROR_INVALID_CHALLENGE_TYPE = -134,
    HKS_ERROR_INVALID_ACCESS_TYPE = -135,
    HKS_ERROR_INVALID_AUTH_TOKEN = -136,
    HKS_ERROR_INVALID_SECURE_SIGN_TYPE = -137,
    HKS_ERROR_NEED_SKIP_ACCESS_CONTROL = -138,
    HKS_ERROR_DEVICE_PASSWORD_UNSET = -139,
    HKS_ERROR_NOT_SYSTEM_APP = -140,
    HKS_ERROR_EXCEED_LIMIT = -141,
    HKS_ERROR_UPGRADE_FAIL = -142,
    HKS_ERROR_INVALID_ACCOUNT_INFO = -143,
    HKS_ERROR_CORRUPT_FILE = -144,
    HKS_ERROR_KEY_NODE_NOT_FOUND = -145,
    HKS_ERROR_KEY_NODE_IN_USE = -146,
    HKS_ERROR_RETRYABLE_ERROR = -147,
    HKS_ERROR_TRUST_RING_DECRYPT_FAILED = -148,
    HKS_ERROR_KEY_CLEAR_FAILED = -149,
    HKS_ERROR_KEY_CONFLICT = -150,
    HKS_ERROR_EMPTY_BASE64_STRING = -151,
    HKS_ERROR_ACCESS_OTHER_USER_KEY = -152,

    HKS_ERROR_NEW_INVALID_ARGUMENT = -997,
    HKS_ERROR_LOAD_PLUGIN_FAIL = -998,
    HKS_ERROR_INTERNAL_ERROR = -999,
    HKS_ERROR_UNKNOWN_ERROR = -1000,
};

/**
 * @brief hks err code
 */
enum HksErrCode {
    HUKS_ERR_CODE_PERMISSION_FAIL = 201,
    HUKS_ERR_CODE_NOT_SYSTEM_APP = 202,
    HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401,
    HUKS_ERR_CODE_NOT_SUPPORTED_API = 801,

    HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001,
    HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002,
    HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003,
    HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004,
    HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005,
    HUKS_ERR_CODE_CRYPTO_FAIL = 12000006,
    HUKS_ERR_CODE_KEY_AUTH_PERMANENTLY_INVALIDATED = 12000007,
    HUKS_ERR_CODE_KEY_AUTH_VERIFY_FAILED = 12000008,
    HUKS_ERR_CODE_KEY_AUTH_TIME_OUT = 12000009,
    HUKS_ERR_CODE_SESSION_LIMIT = 12000010,
    HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011,
    HUKS_ERR_CODE_EXTERNAL_ERROR = 12000012,
    HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST = 12000013,
    HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014,
    HUKS_ERR_CODE_CALL_SERVICE_FAILED = 12000015,
    HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET = 12000016,
    HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018,
};

#ifdef __cplusplus
}
#endif

#endif /* HKS_ERROR_CODE_H */
