/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
sequenceable HksCppParamset..CppParamSet;
interface OHOS.Security.Huks.IHuksAccessExtBase {

    [ipccode 1] void OpenRemoteHandle([in] String index, [in] CppParamSet params, [out] String handle, [out] int errcode);
    [ipccode 2] void CloseRemoteHandle([in] String handle, [in] CppParamSet params, [out] int errcode);
    [ipccode 3] void AuthUkeyPin([in] String handle, [in] CppParamSet params, [out] int errcode, [out] int authState, [out] unsigned int retryCnt);
    [ipccode 4] void GetUkeyPinAuthState([in] String handle, [in] CppParamSet params, [out] unsigned int state, [out] int errcode);
    [ipccode 5] void Sign([in] String handle, [in] CppParamSet params, [in] unsigned char[] inData, [out] unsigned char[] outData, [out] int errcode);
    [ipccode 6] void Verify([in] String handle, [in] CppParamSet params, [in] unsigned char[] plainText, [in] unsigned char[] signature, [out] int errcode);
    [ipccode 7] void ExportCertificate([in] String index, [in] CppParamSet params, [out] String certJsonArr, [out] int errcode);
    [ipccode 8] void ExportProviderCertificates([in] CppParamSet params, [out] String certJsonArr, [out] int errcode);
}
